# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jsonservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='jsonservice.proto',
  package='jsonservice',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11jsonservice.proto\x12\x0bjsonservice\"#\n\x0bJSONREQUEST\x12\x14\n\x0cjson_message\x18\x01 \x01(\t\"$\n\x0cJSONRESPONSE\x12\x14\n\x0cjson_message\x18\x01 \x01(\t2\x9e\x01\n\x0bJSONSERVICE\x12\x41\n\x08get_json\x12\x18.jsonservice.JSONREQUEST\x1a\x19.jsonservice.JSONRESPONSE\"\x00\x12L\n\x0fget_json_stream\x12\x18.jsonservice.JSONREQUEST\x1a\x19.jsonservice.JSONRESPONSE\"\x00(\x01\x30\x01\x62\x06proto3'
)




_JSONREQUEST = _descriptor.Descriptor(
  name='JSONREQUEST',
  full_name='jsonservice.JSONREQUEST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='json_message', full_name='jsonservice.JSONREQUEST.json_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=69,
)


_JSONRESPONSE = _descriptor.Descriptor(
  name='JSONRESPONSE',
  full_name='jsonservice.JSONRESPONSE',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='json_message', full_name='jsonservice.JSONRESPONSE.json_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['JSONREQUEST'] = _JSONREQUEST
DESCRIPTOR.message_types_by_name['JSONRESPONSE'] = _JSONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JSONREQUEST = _reflection.GeneratedProtocolMessageType('JSONREQUEST', (_message.Message,), {
  'DESCRIPTOR' : _JSONREQUEST,
  '__module__' : 'jsonservice_pb2'
  # @@protoc_insertion_point(class_scope:jsonservice.JSONREQUEST)
  })
_sym_db.RegisterMessage(JSONREQUEST)

JSONRESPONSE = _reflection.GeneratedProtocolMessageType('JSONRESPONSE', (_message.Message,), {
  'DESCRIPTOR' : _JSONRESPONSE,
  '__module__' : 'jsonservice_pb2'
  # @@protoc_insertion_point(class_scope:jsonservice.JSONRESPONSE)
  })
_sym_db.RegisterMessage(JSONRESPONSE)



_JSONSERVICE = _descriptor.ServiceDescriptor(
  name='JSONSERVICE',
  full_name='jsonservice.JSONSERVICE',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=110,
  serialized_end=268,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_json',
    full_name='jsonservice.JSONSERVICE.get_json',
    index=0,
    containing_service=None,
    input_type=_JSONREQUEST,
    output_type=_JSONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_json_stream',
    full_name='jsonservice.JSONSERVICE.get_json_stream',
    index=1,
    containing_service=None,
    input_type=_JSONREQUEST,
    output_type=_JSONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_JSONSERVICE)

DESCRIPTOR.services_by_name['JSONSERVICE'] = _JSONSERVICE

# @@protoc_insertion_point(module_scope)
